include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    sort_unnamed_constructors_first: warning
    invalid_assignment: warning
    missing_return: error
    invalid_annotation_target: ignore
    dead_code: info

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
