name: notepad
description: Note App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  asuka: ^2.0.1+3
  auto_route: ^7.8.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.13
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  icons_launcher: ^2.0.6
  injectable: ^2.2.0
  intl: ^0.18.1
  rx_notifier: ^2.2.0+2
  share_plus: ^6.3.0
  shimmer: ^3.0.0
  sqflite: ^2.2.0+3
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  injectable_generator: ^2.3.0

flutter_icons:
  image_path: "assets/icon/ic_logo.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/
