name: notepad
description: Note App

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^5.0.4
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.19.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  uuid: ^4.3.3

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/ic_logo.png"
    background_color: "#FFD717"
    theme_color: "#e6ee9b"
  windows:
    generate: true
    image_path: "assets/icon/ic_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/ic_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
