name: notedup
description: A new Note App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets\icons\keep_up_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/image/
