name: notepad
description: Note App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: 3.3.8

dependencies:
  asuka: ^2.0.1+3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.13
  icons_launcher: ^1.1.7
  rx_notifier: ^1.1.0
  share_plus: ^6.3.0
  sqflite: ^2.2.0+3
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/ic_logo.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/
