// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbanKq5XDtJW_q0U7QDMPuc8Qm5FT1to',
    appId: '1:455982573353:android:d29df9ea4685612d027938',
    messagingSenderId: '455982573353',
    projectId: 'notepad-flutter-fire',
    storageBucket: 'notepad-flutter-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBgCoNNuWyBqmsYMUzpm-MWPxRvcSsEo',
    appId: '1:455982573353:ios:8826fa95149bd866027938',
    messagingSenderId: '455982573353',
    projectId: 'notepad-flutter-fire',
    storageBucket: 'notepad-flutter-fire.appspot.com',
    iosClientId: '455982573353-3dc6hcbe9959gvnhe5a63ri6e5muqoi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepad',
  );
}
